blank_issues_enabled: false

contact_links:

  - name: Contribution Guide
    url: https://website.com/contributing
    about: Please read before opening issues or PRs.  

  - name: Questions/Support (Discussions)
    url: https://github.com/<org>/<repo>/discussions
    about: For how-to questions, use Discussions instead of issues.  

# Optional:
# Add default labels that are added to every issue if no template is chosen
default_labels: ["question"]